version: "3"
services:
  operator1:
    image: ssv-dkg:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    networks:
      - shared_network
    ports:
      - "3030:3030"
    command:
      ["start-operator", "--configPath", "/data/config/operator1.example.yaml"]
    volumes:
      - ./examples:/data

  operator2:
    image: ssv-dkg:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    networks:
      - shared_network
    ports:
      - "3031:3030"
    command:
      ["start-operator", "--configPath", "/data/config/operator2.example.yaml"]
    volumes:
      - ./examples:/data

  operator3:
    image: ssv-dkg:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    networks:
      - shared_network
    ports:
      - "3032:3030"
    command:
      ["start-operator", "--configPath", "/data/config/operator3.example.yaml"]
    volumes:
      - ./examples:/data

  operator4:
    image: ssv-dkg:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    networks:
      - shared_network
    ports:
      - "3033:3030"
    command:
      ["start-operator", "--configPath", "/data/config/operator4.example.yaml"]
    volumes:
      - ./examples:/data

  operator5:
    image: ssv-dkg:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    networks:
      - shared_network
    ports:
      - "3034:3030"
    command:
      ["start-operator", "--configPath", "/data/config/operator5.example.yaml"]
    volumes:
      - ./examples:/data

  operator6:
    image: ssv-dkg:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    networks:
      - shared_network
    ports:
      - "3035:3030"
    command:
      ["start-operator", "--configPath", "/data/config/operator6.example.yaml"]
    volumes:
      - ./examples:/data

  operator7:
    image: ssv-dkg:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    networks:
      - shared_network
    ports:
      - "3036:3030"
    command:
      ["start-operator", "--configPath", "/data/config/operator7.example.yaml"]
    volumes:
      - ./examples:/data

  operator8:
    image: ssv-dkg:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    networks:
      - shared_network
    ports:
      - "3037:3030"
    command:
      ["start-operator", "--configPath", "/data/config/operator8.example.yaml"]
    volumes:
      - ./examples:/data

  operator9:
    image: ssv-dkg:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    networks:
      - shared_network
    ports:
      - "3038:3030"
    command: ["start-operator", "--configPath", "/data/operator9/config"]
    volumes:
      - ./examples:/data

  operator10:
    image: ssv-dkg:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    networks:
      - shared_network
    ports:
      - "3039:3030"
    command: ["start-operator", "--configPath", "/data/operator10/config"]
    volumes:
      - ./examples:/data

  operator11:
    image: ssv-dkg:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    networks:
      - shared_network
    ports:
      - "3040:3030"
    command: ["start-operator", "--configPath", "/data/operator11/config"]
    volumes:
      - ./examples:/data

  operator12:
    image: ssv-dkg:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    networks:
      - shared_network
    ports:
      - "3041:3030"
    command: ["start-operator", "--configPath", "/data/operator12/config"]
    volumes:
      - ./examples:/data

  operator13:
    image: ssv-dkg:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    networks:
      - shared_network
    ports:
      - "3042:3030"
    command: ["start-operator", "--configPath", "/data/operator13/config"]
    volumes:
      - ./examples:/data

  initiator:
    image: ssv-dkg:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    depends_on:
      - operator1
      - operator2
      - operator3
      - operator4
      - operator5
      - operator6
      - operator7
      - operator8
      - operator9
      - operator10
    networks:
      - shared_network
    command: ["init", "--configPath", "/data/config/initiator.example.yaml"]
    volumes:
      - ./examples:/data

  ping:
    image: ssv-dkg:latest
    depends_on:
      - operator1
      - operator2
      - operator3
      - operator4
      - operator5
      - operator6
      - operator7
      - operator8
      - operator9
      - operator10
      - operator11
      - operator12
      - operator13
    networks:
      - shared_network
    command:
      [
        "ping",
        "--ip",
        "https://operator1:3030,https://operator2:3030,https://operator3:3030,https://operator4:3030",
      ]
    volumes:
      - ./examples:/data

networks:
  shared_network:
