version: "3"
services:
  ethnode:
    image: ethereum/client-go:stable
    networks:
      - shared_network
    ports:
      - "8545:8545"
      - "30303:30303"
    command:
      [
        "--holesky",
        "--ipcdisable",
        "--http",
        "--http.addr",
        "0.0.0.0",
        "--http.port",
        "8545",
        "--http.vhosts=*",
      ]
  operator1:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3030:3030"
    command:
      ["start-operator", "--configPath", "/data/config/operator1.example.yaml"]
    volumes:
      - ./examples:/data

  operator2:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3031:3030"
    command:
      ["start-operator", "--configPath", "/data/config/operator2.example.yaml"]
    volumes:
      - ./examples:/data

  operator3:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3032:3030"
    command:
      ["start-operator", "--configPath", "/data/config/operator3.example.yaml"]
    volumes:
      - ./examples:/data

  operator4:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3033:3030"
    command:
      ["start-operator", "--configPath", "/data/config/operator4.example.yaml"]
    volumes:
      - ./examples:/data

  operator5:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3034:3030"
    command:
      ["start-operator", "--configPath", "/data/config/operator5.example.yaml"]
    volumes:
      - ./examples:/data

  operator6:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3035:3030"
    command:
      ["start-operator", "--configPath", "/data/config/operator6.example.yaml"]
    volumes:
      - ./examples:/data

  operator7:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3036:3030"
    command:
      ["start-operator", "--configPath", "/data/config/operator7.example.yaml"]
    volumes:
      - ./examples:/data

  operator8:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3037:3030"
    command:
      ["start-operator", "--configPath", "/data/config/operator8.example.yaml"]
    volumes:
      - ./examples:/data

  initiator:
    image: ssv-dkg:latest
    depends_on:
      - operator1
      - operator2
      - operator3
      - operator4
    networks:
      - shared_network
    command: ["init", "--configPath", "/data/config/initiator.example.yaml"]
    volumes:
      - ./examples:/data

  resign:
    image: ssv-dkg:latest
    depends_on:
      - operator1
      - operator2
      - operator3
      - operator4
    networks:
      - shared_network
    command: ["resign", "--configPath", "/data/config/resign.example.yaml"]
    volumes:
      - ./examples:/data

  reshare:
    image: ssv-dkg:latest
    depends_on:
      - ethnode
      - operator1
      - operator2
      - operator3
      - operator4
      - operator5
      - operator6
      - operator7
      - operator8
    networks:
      - shared_network
    command: ["reshare", "--configPath", "/data/config/reshare.example.yaml"]
    volumes:
      - ./examples:/data

  ping:
    image: ssv-dkg:latest
    depends_on:
      - operator1
      - operator2
      - operator3
      - operator4
    networks:
      - shared_network
    command:
      [
        "ping",
        "--ip",
        "https://operator1:3030,https://operator2:3030,https://operator3:3030,https://operator4:3030",
      ]
    volumes:
      - ./examples:/data

networks:
  shared_network:
