version: "3"
services:
  operator1:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3030:3030"
    entrypoint: /app
    command:
      ["start-operator", "--configYAML", "/data/config/operator1.example.yaml"]
    volumes:
      - ./examples:/data

  operator2:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3031:3030"
    entrypoint: /app
    command:
      ["start-operator", "--configYAML", "/data/config/operator2.example.yaml"]
    volumes:
      - ./examples:/data

  operator3:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3032:3030"
    entrypoint: /app
    command:
      ["start-operator", "--configYAML", "/data/config/operator3.example.yaml"]
    volumes:
      - ./examples:/data

  operator4:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3033:3030"
    entrypoint: /app
    command:
      ["start-operator", "--configYAML", "/data/config/operator4.example.yaml"]
    volumes:
      - ./examples:/data

  operator5:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3034:3030"
    entrypoint: /app
    command:
      ["start-operator", "--configYAML", "/data/config/operator5.example.yaml"]
    volumes:
      - ./examples:/data

  operator6:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3035:3030"
    entrypoint: /app
    command:
      ["start-operator", "--configYAML", "/data/config/operator6.example.yaml"]
    volumes:
      - ./examples:/data

  operator7:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3036:3030"
    entrypoint: /app
    command:
      ["start-operator", "--configYAML", "/data/config/operator7.example.yaml"]
    volumes:
      - ./examples:/data

  operator8:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3037:3030"
    entrypoint: /app
    command:
      ["start-operator", "--configYAML", "/data/config/operator8.example.yaml"]
    volumes:
      - ./examples:/data

  initiator:
    image: ssv-dkg:latest
    depends_on:
      - operator1
      - operator2
      - operator3
      - operator4
    networks:
      - shared_network
    entrypoint: /app
    command: ["init", "--configYAML", "/data/config/initiator.example.yaml"]
    volumes:
      - ./examples:/data

  resharing:
    image: ssv-dkg:latest
    depends_on:
      - operator1
      - operator2
      - operator3
      - operator4
      - operator5
      - operator6
      - operator7
      - operator8
    networks:
      - shared_network
    entrypoint: /app
    command: ["reshare", "--configYAML", "/data/config/reshare.example.yaml"]
    volumes:
      - ./examples:/data

networks:
  shared_network:
