version: "3"
services:
  operator1:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3030:3030"
    entrypoint: /app
    command:
      ["start-operator", "--configPath", "/data/config/operator1.example.yaml"]
    volumes:
      - ./examples:/data

  operator2:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3031:3030"
    entrypoint: /app
    command:
      ["start-operator", "--configPath", "/data/config/operator2.example.yaml"]
    volumes:
      - ./examples:/data

  operator3:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3032:3030"
    entrypoint: /app
    command:
      ["start-operator", "--configPath", "/data/config/operator3.example.yaml"]
    volumes:
      - ./examples:/data

  operator4:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3033:3030"
    entrypoint: /app
    command:
      ["start-operator", "--configPath", "/data/config/operator4.example.yaml"]
    volumes:
      - ./examples:/data

  initiator:
    image: ssv-dkg:latest
    depends_on:
      - operator1
      - operator2
      - operator3
      - operator4
    networks:
      - shared_network
    entrypoint: /app
    command: ["init", "--configPath", "/data/config/initiator.example.yaml"]
    volumes:
      - ./examples:/data

networks:
  shared_network:
