version: "3"
services:
  operator1:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3030:3030"
    entrypoint: /app
    command: ["start-operator", "--configPath", "/data/operator1/config"]
    volumes:
      - ./examples:/data

  operator2:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3031:3030"
    entrypoint: /app
    command: ["start-operator", "--configPath", "/data/operator2/config"]
    volumes:
      - ./examples:/data

  operator3:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3032:3030"
    entrypoint: /app
    command: ["start-operator", "--configPath", "/data/operator3/config"]
    volumes:
      - ./examples:/data

  operator4:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3033:3030"
    entrypoint: /app
    command: ["start-operator", "--configPath", "/data/operator4/config"]
    volumes:
      - ./examples:/data

  operator5:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3034:3030"
    entrypoint: /app
    command: ["start-operator", "--configPath", "/data/operator5/config"]
    volumes:
      - ./examples:/data

  operator6:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3035:3030"
    entrypoint: /app
    command: ["start-operator", "--configPath", "/data/operator6/config"]
    volumes:
      - ./examples:/data

  operator7:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3036:3030"
    entrypoint: /app
    command: ["start-operator", "--configPath", "/data/operator7/config"]
    volumes:
      - ./examples:/data

  operator8:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3037:3030"
    entrypoint: /app
    command: ["start-operator", "--configPath", "/data/operator8/config"]
    volumes:
      - ./examples:/data

  initiator:
    image: ssv-dkg:latest
    depends_on:
      - operator1
      - operator2
      - operator3
      - operator4
    networks:
      - shared_network
    entrypoint: /app
    command: ["init", "--configPath", "/data/initiator/config"]
    volumes:
      - ./examples:/data

  resharing:
    image: ssv-dkg:latest
    depends_on:
      - operator1
      - operator2
      - operator3
      - operator4
      - operator5
      - operator6
      - operator7
      - operator8
    networks:
      - shared_network
    entrypoint: /app
    command: ["reshare", "--configPath", "/data/initiator/config"]
    volumes:
      - ./examples:/data

  ping:
    image: ssv-dkg:latest
    depends_on:
      - operator1
      - operator2
      - operator3
      - operator4
    networks:
      - shared_network
    entrypoint: /app
    command:
      [
        "ping",
        "--ip",
        "http://operator1:3030,http://operator2:3030,http://operator3:3030,http://operator4:3030",
      ]
    volumes:
      - ./examples:/data

networks:
  shared_network:
