---
apiVersion: v1
kind: Service
metadata:
  name: ssv-dkg-64-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-dkg-64
spec:
  type: ClusterIP
  ports:
    - port: 3064
      protocol: TCP
      targetPort: 3064
      name: port-3064
  selector:
    app: ssv-dkg-64
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-dkg-64
  name: ssv-dkg-64
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  selector:
    matchLabels:
      app: ssv-dkg-64
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ssv-dkg-64
    spec:
      containers:
      - name: ssv-dkg-64
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT
        ports:
        - containerPort: 3064
        command: ["/bin/ssv-dkg", "start-operator", "--configPath=/data/config", "--privKeyPassword=/data/password", "--privKey=/data/encrypted_private_key_op64.json", "--operatorID=64"]
        volumeMounts:
        - name: secrets-file
          mountPath: "/data/encrypted_private_key_op64.json"
          subPath: encrypted_private_key_op64.json
        - name: ssv-dkg-64-cm
          mountPath: /data/password
          subPath: password
        - name: ssv-dkg-64-cm
          mountPath: /data/config/config.yaml
          subPath: operator.yaml
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: secrets-file
          secret:
            secretName: ssv-dkg-64
        - name: ssv-dkg-64-cm
          configMap:
            name: ssv-dkg-64-cm
      hostNetwork: true
