privKey: /data/operator9/encrypted_private_key.json
privKeyPassword: /data/operator9/password
port: 3030
operatorID: 9
logLevel: debug
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/operator9/output/operator9_logs_debug.log
DBPath: /data/operator9/output/operator9_db/
outputPath: /data/operator9/output
