operatorIDs: [1, 2, 3, 4]
withdrawAddress: "0000000000000000000000000000000000000009"
owner: "0x81592c3de184a3e2c0dcb5a261bc107bfa91f494"
nonce: 4
fork: "mainnet"
operatorsInfoPath: /data/docker_operators.json
depositResultsPath: /data/deposit.json
ssvPayloadResultsPath: /data/payload.json
initiatorPrivKey: /data/initiator/encrypted_private_key.json
initiatorPrivKeyPassword: /data/initiator/password
