privKey: /data/operator2/encrypted_private_key.json
privKeyPassword: /data/operator2/password
port: 3030
storeShare: false
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/output/operator2_logs_debug.log
DBPath: /data/output/operator2_db/
outputPath: /data/output
