privKey: /data/operator3/encrypted_private_key.json
password: /data/operator3/password
port: 3030
storeShare: false
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/output/operator3_logs_debug.log
outputPath: /data/output