privKey: /data/operator1/encrypted_private_key.json
password: /data/operator1/password
port: 3030
storeShare: false
logLevel: debug
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/output/operator1_logs/debug.log
DBPath: /data/output/operator1_db/