privKey: /data/operator2/encrypted_private_key.json
password: /data/operator2/password
port: 3030
storeShare: false
logLevel: debug
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/output/operator2_logs/debug.log
DBPath: /data/output/operator2_db/
