privKey: /data/operator5/encrypted_private_key.json
privKeyPassword: /data/operator5/password
port: 3030
storeShare: false
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/output/operator5_logs_debug.log
DBPath: /data/output/operator5_db/
configPath: /data/config