privKey: /data/operator7/encrypted_private_key.json
privKeyPassword: /data/operator7/password
port: 3030
operatorID: 7
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/operator7/output/operator7_logs_debug.log
outputPath: /data/operator7/output