privKey: /data/operator8/encrypted_private_key.json
password: /data/operator8/password
port: 3030
storeShare: false
logLevel: debug
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/output/operator8_logs/debug.log
DBPath: /data/output/operator8_db/