privKey: /data/operator3/encrypted_private_key.json
privKeyPassword: /data/operator3/password
port: 3030
operatorID: 33
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/operator3/output/operator3_logs_debug.log
outputPath: /data/operator3/output
serverTLSCertPath: /data/operator3/localhost.crt
serverTLSKeyPath: /data/operator3/localhost.key