operatorPrivKey: /data/operator1/encrypted_private_key.json
operatorPrivKeyPassword: /data/operator1/password
port: 3030
storeShare: false
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/output/operator1_logs_debug.log
DBPath: /data/output/operator1_db/
outputPath: /data/output
