privKey: /data/operator6/encrypted_private_key.json
privKeyPassword: /data/operator6/password
port: 3030
storeShare: false
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/output/operator6_logs_debug.log
DBPath: /data/output/operator6_db/
configPath: /data/config