operatorPrivKey: /data/operator4/encrypted_private_key.json
operatorPrivKeyPassword: /data/operator4/password
port: 3030
storeShare: false
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/output/operator4_logs_debug.log
DBPath: /data/output/operator4_db/
outputPath: /data/output
