privKey: /data/operator8/encrypted_private_key.json
privKeyPassword: /data/operator8/password
port: 3030
operatorID: 8
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/operator8/output/operator8_logs_debug.log
DBPath: /data/operator8/output/operator8_db/
outputPath: /data/operator8/output
