operatorIDs: [1, 2, 3, 4]
newOperatorIDs: [5, 6, 7, 8]
oldID: "6f102607bc9f483ba776309470947d11443f4942a316c681"
owner: "0x81592c3de184a3e2c0dcb5a261bc107bfa91f494"
nonce: 0
network: "mainnet"
operatorsInfoPath: /data/operators_info.json
outputPath: /data/output
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/output/initiator_debug.log
configPath: /data/config
