operatorIDs: [1, 2, 3, 4]
newOperatorIDs: [5, 6, 7, 8]
oldID: "737d101264e64182bb05c9145f90d9c8b8034131a7c7e51e"
owner: "0x81592c3de184a3e2c0dcb5a261bc107bfa91f494"
nonce: 0
network: "holesky"
operatorsInfoPath: /data/initiator/operators_info.json
outputPath: /data/initiator/output
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/initiator/output/initiator_debug.log
