privKey: /data/operator2/encrypted_private_key.json
privKeyPassword: /data/operator2/password
port: 3030
operatorID: 2
storeShare: false
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/operator2/output/operator2_logs_debug.log
DBPath: /data/operator2/output/operator2_db/
outputPath: /data/operator2/output
