privKey: /data/operator12/encrypted_private_key.json
privKeyPassword: /data/operator12/password
port: 3030
operatorID: 12
logLevel: debug
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/operator12/output/operator12_logs_debug.log
DBPath: /data/operator12/output/operator12_db/
outputPath: /data/operator12/output
